import type { TravelPackage } from "@/types/travel-package";

// Curated halal-friendly travel packages for Malaysian Muslim travellers.
// Pricing is per-pax twin-share in MYR, all-in (flights + land + visa where
// applicable). Competitor ranges reflect 2025-2026 retail rates from major
// Malaysian agencies (Andalusia, Tabung Haji Travel, Mutiara Mas, TH Travel,
// Tripfez, Halal Trip, etc.). `priceMyr` is set to undercut the lower bound
// of competitor pricing while preserving margin via group buys and shoulder-
// season departures.

export const halalTravelPackages: TravelPackage[] = [
  {
    slug: "umrah-9d-economy-madinah-makkah",
    title: "Umrah Ekonomi 9H — Madinah & Makkah",
    destinationCountries: ["Saudi Arabia"],
    durationDays: 9,
    durationNights: 7,
    region: "middle_east",
    halalTier: "muslim_majority",
    audiences: ["religious", "family", "senior"],
    priceMyr: 6990,
    competitorPriceLowMyr: 7500,
    competitorPriceHighMyr: 9800,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "Direct flight KUL-JED-KUL (Saudia/Malaysia Airlines)",
      "4-star hotel <500m from Masjid Nabawi (3 nights)",
      "4-star hotel <600m from Masjidil Haram (4 nights)",
      "Full-board buffet, all meals halal",
      "Licensed mutawwif (Malay-speaking)",
      "Umrah visa, vaccination, ihram set",
      "Ziarah Madinah & Makkah by AC coach",
    ],
    exclusions: ["Personal expenses", "Optional Taif day trip (RM 180)"],
    highlights: [
      "Two umrah opportunities included",
      "Walking distance to both Haramain",
      "Tausiah harian by ustaz",
    ],
    itinerarySummary: [
      "Day 1: KUL > Madinah, check-in",
      "Day 2-3: Ibadah & ziarah Madinah",
      "Day 4: Bertolak ke Makkah, niat Umrah di Bir Ali",
      "Day 5-7: Umrah & ibadah di Masjidil Haram",
      "Day 8: Ziarah Makkah",
      "Day 9: JED > KUL",
    ],
    prayerFacilities: "Holy cities — mosque adjacent to hotel",
    halalFoodNotes: "100% halal; Malaysian/Indonesian menu rotation",
    visaNotes: "Umrah visa arranged by agency; passport >7 months validity",
    bestMonths: ["Feb", "Mar", "Apr", "Sep", "Oct", "Nov"],
    minPax: 25,
    demand: "very_high",
    rationale:
      "Largest single-segment outbound demand from Malaysia (~250k Umrah pax/yr). Group-buy on Saudia bulk fares + shoulder-season departure undercuts retail by ~RM 500-2,800.",
  },
  {
    slug: "turkey-9d-istanbul-cappadocia-bursa",
    title: "Turki 9H — Istanbul, Cappadocia, Bursa",
    destinationCountries: ["Turkey"],
    durationDays: 9,
    durationNights: 7,
    region: "europe",
    halalTier: "muslim_majority",
    audiences: ["family", "honeymoon", "heritage"],
    priceMyr: 4290,
    competitorPriceLowMyr: 4800,
    competitorPriceHighMyr: 6200,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "Turkish Airlines KUL-IST return",
      "4-star halal-certified hotels (Crystal/Grand Makel tier)",
      "Daily halal breakfast + dinner",
      "Domestic flight IST-Cappadocia",
      "Bosphorus cruise, Topkapi, Hagia Sophia, Blue Mosque",
      "Pamukkale optional add-on",
      "Malay-speaking tour leader from KL",
    ],
    exclusions: ["Hot air balloon (USD 220)", "Lunches", "Tipping (USD 40)"],
    highlights: [
      "Solat di Masjid Sultan Ahmed, Sulaimaniye, Eyup Sultan",
      "Cappadocia underground city + cave hotel option",
      "Bursa Grand Mosque & Iskender kebab",
    ],
    itinerarySummary: [
      "Day 1-2: KUL > Istanbul, ziarah masjid bersejarah",
      "Day 3: Bursa day trip",
      "Day 4-5: Fly Cappadocia, Goreme & Kaymakli",
      "Day 6: Konya (Mevlana) > Ankara",
      "Day 7-8: Istanbul old city + Grand Bazaar",
      "Day 9: IST > KUL",
    ],
    prayerFacilities: "Mosques every 200m; azan audible everywhere",
    halalFoodNotes: "Entire country halal; agency uses MUI-aware caterers",
    visaNotes: "e-Visa free for Malaysian passport (90 days)",
    bestMonths: ["Apr", "May", "Sep", "Oct"],
    minPax: 20,
    demand: "very_high",
    rationale:
      "Top-3 Muslim-friendly long-haul destination for MY market. Visa-free + THY direct flight + tulip/autumn shoulder pricing yields RM 500+ saving vs. listed competitors.",
  },
  {
    slug: "bandung-shopping-4d-budget",
    title: "Bandung Shopping & Kuliner 4H",
    destinationCountries: ["Indonesia"],
    durationDays: 4,
    durationNights: 3,
    region: "southeast_asia",
    halalTier: "muslim_majority",
    audiences: ["shopping", "family"],
    priceMyr: 690,
    competitorPriceLowMyr: 850,
    competitorPriceHighMyr: 1290,
    savingsVsMarketMyr: 160,
    currency: "MYR",
    inclusions: [
      "AirAsia KUL-BDO return",
      "3-star hotel near Cihampelas (3 nights)",
      "Halal breakfast daily",
      "Factory outlet & Pasar Baru transfers",
      "Tangkuban Perahu + Kawah Putih day tour",
      "Malay-speaking driver-guide",
    ],
    exclusions: ["Lunch & dinner", "Personal shopping"],
    highlights: [
      "Branded factory outlets at 30-50% off",
      "Halal Sundanese cuisine (Sapulidi, Ampera)",
      "Cool highland weather year-round",
    ],
    itinerarySummary: [
      "Day 1: KUL > Bandung, Cihampelas walk",
      "Day 2: Lembang highlands, Tangkuban Perahu",
      "Day 3: Pasar Baru + Rumah Mode shopping",
      "Day 4: Pasalat ke airport > KUL",
    ],
    prayerFacilities: "Surau in every mall; mosque <100m from hotel",
    halalFoodNotes: "Default halal; avoid Chinese-Indonesian babi outlets",
    visaNotes: "Visa-free 30 days for Malaysians",
    bestMonths: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    minPax: 2,
    demand: "very_high",
    rationale:
      "Highest-frequency MY outbound short-haul. Sub-RM 700 all-in beats budget OTAs which typically sell at RM 850+. Repeat-customer driver for the platform.",
  },
  {
    slug: "bosnia-croatia-balkan-10d",
    title: "Balkan Muslim Heritage 10H — Bosnia, Kroatia, Montenegro",
    destinationCountries: ["Bosnia and Herzegovina", "Croatia", "Montenegro"],
    durationDays: 10,
    durationNights: 8,
    region: "balkans",
    halalTier: "muslim_majority",
    audiences: ["heritage", "family", "honeymoon"],
    priceMyr: 6490,
    competitorPriceLowMyr: 7200,
    competitorPriceHighMyr: 9500,
    savingsVsMarketMyr: 710,
    currency: "MYR",
    inclusions: [
      "Turkish Airlines KUL-IST-SJJ return",
      "4-star halal-friendly hotels",
      "Halal breakfast + dinner daily",
      "Sarajevo, Mostar, Pocitelj, Travnik, Jajce",
      "Day trip to Dubrovnik (Croatia) & Kotor (Montenegro)",
      "Malay tour leader",
    ],
    exclusions: ["Lunches", "Schengen visa (n/a — none required)"],
    highlights: [
      "Solat di Masjid Gazi Husrev-beg",
      "Stari Most Mostar (UNESCO)",
      "Plitvice Lakes optional add-on",
    ],
    itinerarySummary: [
      "Day 1-2: KUL > Sarajevo via IST",
      "Day 3-4: Sarajevo old town + Tunnel of Hope",
      "Day 5: Mostar & Pocitelj",
      "Day 6: Dubrovnik day trip",
      "Day 7: Kotor (Montenegro)",
      "Day 8-9: Jajce, Travnik, Sarajevo bazaar",
      "Day 10: SJJ > KUL",
    ],
    prayerFacilities: "Bosnia 50% Muslim; mosques in every town",
    halalFoodNotes: "Bosnian cuisine natively halal (cevapi, burek)",
    visaNotes: "All three countries visa-free for Malaysians",
    bestMonths: ["May", "Jun", "Sep", "Oct"],
    minPax: 15,
    demand: "rising",
    rationale:
      "Trending hard post-2023 — TikTok-driven demand. Visa-free trifecta + EUR weakness vs. MYR enables sub-RM 6,500 pricing where competitors cluster at RM 7,200-9,500.",
  },
  {
    slug: "uzbekistan-silk-road-8d",
    title: "Uzbekistan Silk Road 8H — Tashkent, Samarkand, Bukhara",
    destinationCountries: ["Uzbekistan"],
    durationDays: 8,
    durationNights: 6,
    region: "central_asia",
    halalTier: "muslim_majority",
    audiences: ["heritage", "religious", "senior"],
    priceMyr: 4990,
    competitorPriceLowMyr: 5500,
    competitorPriceHighMyr: 7200,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "Asiana/Korean Air KUL-ICN-TAS return",
      "4-star hotels in Tashkent, Samarkand, Bukhara",
      "Full-board halal meals",
      "High-speed Afrosiyob train Tashkent-Samarkand-Bukhara",
      "Imam Bukhari shrine, Shah-i-Zinda, Registan, Bibi-Khanym",
      "Malay-speaking ustaz tour leader",
    ],
    exclusions: ["Tipping (USD 50)", "Optional Khiva extension"],
    highlights: [
      "Ziarah makam Imam Bukhari & Imam Tirmidzi",
      "Solat di Bibi-Khanym (built by Timur)",
      "Registan Square — heart of Islamic golden age",
    ],
    itinerarySummary: [
      "Day 1-2: KUL > Tashkent, Hazrat Imam complex",
      "Day 3: Train to Samarkand",
      "Day 4: Samarkand — Registan, Gur-e-Amir, Ulugh Beg",
      "Day 5: Train to Bukhara",
      "Day 6: Bukhara — Poi-Kalyan, Ark fortress",
      "Day 7: Return Tashkent",
      "Day 8: TAS > KUL",
    ],
    prayerFacilities: "96% Muslim country; mosques everywhere",
    halalFoodNotes: "All restaurants halal; pilaf, samsa, lagman",
    visaNotes: "Visa-free 30 days for Malaysian passport",
    bestMonths: ["Apr", "May", "Sep", "Oct"],
    minPax: 15,
    demand: "rising",
    rationale:
      "Religious-heritage angle (Imam Bukhari) drives high interest from older MY Muslim demographic. Visa-free since 2018; Afrosiyob train product unique vs. competitors still using bus.",
  },
  {
    slug: "morocco-imperial-cities-10d",
    title: "Maghribi 10H — Casablanca, Fes, Marrakech, Sahara",
    destinationCountries: ["Morocco"],
    durationDays: 10,
    durationNights: 8,
    region: "north_africa",
    halalTier: "muslim_majority",
    audiences: ["heritage", "honeymoon", "adventure"],
    priceMyr: 7990,
    competitorPriceLowMyr: 8500,
    competitorPriceHighMyr: 11500,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "Emirates/Qatar KUL-CMN return",
      "4-star riads & hotels",
      "Halal breakfast + dinner daily",
      "Sahara overnight at Erg Chebbi (Berber camp)",
      "Casablanca Hassan II Mosque, Fes medina, Marrakech",
      "Atlas Mountains via Tizi n'Tichka",
    ],
    exclusions: ["Lunches", "Camel ride tip"],
    highlights: [
      "Solat di Hassan II Mosque (3rd largest in world)",
      "Sahara desert sunrise + stargazing",
      "Fes el-Bali — oldest medina + Al-Qarawiyyin (oldest university)",
    ],
    itinerarySummary: [
      "Day 1-2: KUL > Casablanca",
      "Day 3: Rabat > Chefchaouen (blue city)",
      "Day 4: Fes medina",
      "Day 5: Fes > Merzouga via Ifrane",
      "Day 6: Sahara camp",
      "Day 7: Merzouga > Ouarzazate > Marrakech",
      "Day 8: Marrakech medina + Jemaa el-Fnaa",
      "Day 9: Casablanca",
      "Day 10: CMN > KUL",
    ],
    prayerFacilities: "99% Muslim; azan audible across all cities",
    halalFoodNotes: "All halal; tagine, couscous, pastilla",
    visaNotes: "Visa-free 90 days for Malaysians",
    bestMonths: ["Mar", "Apr", "Oct", "Nov"],
    minPax: 15,
    demand: "rising",
    rationale:
      "Bucket-list Muslim destination with growing MY interest. Direct codeshare via Doha + visa-free advantage; competitors rely on retail Emirates fares we beat with bulk allocation.",
  },
  {
    slug: "egypt-pyramids-nile-9d",
    title: "Mesir 9H — Kaherah, Luxor, Aswan, Iskandariah",
    destinationCountries: ["Egypt"],
    durationDays: 9,
    durationNights: 7,
    region: "middle_east",
    halalTier: "muslim_majority",
    audiences: ["heritage", "religious", "family"],
    priceMyr: 5990,
    competitorPriceLowMyr: 6500,
    competitorPriceHighMyr: 8500,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "EgyptAir KUL-CAI via Bangkok",
      "4-star hotels + 3-night Nile cruise (Luxor-Aswan)",
      "Halal full board",
      "Pyramids of Giza, Sphinx, Egyptian Museum",
      "Karnak, Valley of Kings, Abu Simbel optional",
      "Alexandria day tour",
      "Malay-speaking ustaz",
    ],
    exclusions: ["Camel ride", "Abu Simbel (USD 120)"],
    highlights: [
      "Ziarah Masjid Amr ibn al-As (oldest in Africa)",
      "Solat di Al-Azhar Mosque",
      "Nile felucca cruise at sunset",
    ],
    itinerarySummary: [
      "Day 1-2: KUL > Cairo, Pyramids & Sphinx",
      "Day 3: Islamic Cairo + Khan el-Khalili",
      "Day 4: Fly Luxor, board cruise",
      "Day 5-6: Karnak, Valley of Kings, Edfu, Kom Ombo",
      "Day 7: Aswan + High Dam",
      "Day 8: Alexandria",
      "Day 9: CAI > KUL",
    ],
    prayerFacilities: "90% Muslim; azan from every minaret",
    halalFoodNotes: "Halal default; koshari, ful, kebab",
    visaNotes: "Visa-on-arrival USD 25 for Malaysians",
    bestMonths: ["Oct", "Nov", "Feb", "Mar"],
    minPax: 18,
    demand: "high",
    rationale:
      "Strong religious-heritage demand (Al-Azhar alumni network in MY). Nile cruise inclusion at this price point is unmatched — most competitors quote cruise as add-on.",
  },
  {
    slug: "maldives-halal-honeymoon-4d",
    title: "Maldives Halal Honeymoon 4H — Water Villa",
    destinationCountries: ["Maldives"],
    durationDays: 4,
    durationNights: 3,
    region: "south_asia",
    halalTier: "muslim_majority",
    audiences: ["honeymoon"],
    priceMyr: 2990,
    competitorPriceLowMyr: 3500,
    competitorPriceHighMyr: 5800,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "Malaysia Airlines/AirAsia KUL-MLE return",
      "3 nights overwater bungalow (halal-friendly resort)",
      "Full-board halal meals (no alcohol package)",
      "Speedboat transfers",
      "Snorkeling gear",
      "Bridal cake & decoration",
    ],
    exclusions: ["Spa", "Excursions (sunset cruise USD 80)"],
    highlights: [
      "Maldives is 100% Muslim country",
      "Resort prayer mat + qibla in every villa",
      "No-alcohol resort selection (Reethi Faru / Thoddoo guesthouse option)",
    ],
    itinerarySummary: [
      "Day 1: KUL > Male, speedboat to resort",
      "Day 2-3: Beach + snorkel + sunset",
      "Day 4: Resort > MLE > KUL",
    ],
    prayerFacilities: "Local island option includes mosque <50m",
    halalFoodNotes: "100% halal — country law",
    visaNotes: "Visa-free 30 days for Malaysians",
    bestMonths: ["Jan", "Feb", "Mar", "Apr", "Nov", "Dec"],
    minPax: 2,
    demand: "high",
    rationale:
      "Halal-honeymoon segment underserved — most Maldives packages assume alcohol resorts. Local-island guesthouse arbitrage drops price ~40% vs. resort-only competitors.",
  },
  {
    slug: "dubai-abu-dhabi-family-6d",
    title: "Dubai & Abu Dhabi Family 6H",
    destinationCountries: ["United Arab Emirates"],
    durationDays: 6,
    durationNights: 4,
    region: "middle_east",
    halalTier: "muslim_majority",
    audiences: ["family", "shopping"],
    priceMyr: 2990,
    competitorPriceLowMyr: 3500,
    competitorPriceHighMyr: 4800,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "Emirates KUL-DXB return",
      "4-star hotel Deira/Bur Dubai (4 nights)",
      "Halal breakfast daily",
      "Dubai city tour + Burj Khalifa Level 124",
      "Desert safari (4WD + camp + halal BBQ)",
      "Abu Dhabi day tour — Sheikh Zayed Mosque, Ferrari World",
    ],
    exclusions: [
      "Lunch & dinner (except safari)",
      "Ferrari World ticket (AED 295)",
    ],
    highlights: [
      "Solat di Sheikh Zayed Grand Mosque",
      "Burj Khalifa & Dubai Mall fountain",
      "Desert dune-bashing + tanura show",
    ],
    itinerarySummary: [
      "Day 1: KUL > DXB",
      "Day 2: Dubai city + Burj Khalifa + Dubai Mall",
      "Day 3: Desert safari",
      "Day 4: Abu Dhabi day tour",
      "Day 5: Free / Global Village / Miracle Garden",
      "Day 6: DXB > KUL",
    ],
    prayerFacilities: "Mosques in every mall + hotel; azan public",
    halalFoodNotes: "Effectively all halal; abundant Malay/Indo restaurants",
    visaNotes: "Visa-free 30 days for Malaysians (since 2023)",
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    minPax: 4,
    demand: "very_high",
    rationale:
      "Visa-free policy (2023) + Emirates bulk fare contract = market-disrupting price. Competitors anchor at RM 3,500 with similar inclusions; we ship at RM 2,990 via shoulder weekday departures.",
  },
  {
    slug: "jordan-palestine-aqsa-10d",
    title: "Al-Aqsa & Jordan 10H — Ziarah Masra' Mi'raj",
    destinationCountries: ["Jordan", "Palestine"],
    durationDays: 10,
    durationNights: 8,
    region: "middle_east",
    halalTier: "muslim_majority",
    audiences: ["religious", "heritage"],
    priceMyr: 7990,
    competitorPriceLowMyr: 8800,
    competitorPriceHighMyr: 11200,
    savingsVsMarketMyr: 810,
    currency: "MYR",
    inclusions: [
      "Royal Jordanian/Emirates KUL-AMM return",
      "4-star hotels Amman, Dead Sea, Jerusalem area",
      "Halal full board",
      "Solat & ziarah Masjidil Aqsa, Qubbatus Sakhrah",
      "Petra, Wadi Rum, Dead Sea",
      "Bethlehem, Hebron (Masjid Ibrahimi)",
      "Licensed Palestinian/Jordanian guide + Malay ustaz",
    ],
    exclusions: ["Allenby Bridge crossing fee (USD 60)", "Tipping (USD 80)"],
    highlights: [
      "Solat fardhu di Masjidil Aqsa (qiblat pertama)",
      "Wadi Rum overnight Bedouin camp",
      "Petra — 7 wonders of the world",
    ],
    itinerarySummary: [
      "Day 1-2: KUL > Amman",
      "Day 3: Madaba > Mount Nebo > Dead Sea",
      "Day 4: Petra",
      "Day 5: Wadi Rum desert camp",
      "Day 6: Cross to Palestine via King Hussein bridge",
      "Day 7-8: Al-Aqsa, Old City, Hebron, Bethlehem",
      "Day 9: Return Amman",
      "Day 10: AMM > KUL",
    ],
    prayerFacilities: "Holy land — mosques throughout",
    halalFoodNotes: "All halal Levantine — mansaf, mezze, knafeh",
    visaNotes:
      "Jordan visa-on-arrival (free with Jordan Pass); Israel-controlled crossing for Palestine — agency handles paperwork",
    bestMonths: ["Mar", "Apr", "May", "Sep", "Oct", "Nov"],
    minPax: 18,
    demand: "rising",
    rationale:
      "Aqsa pilgrimage is bucket-list segment with consistent demand floor. Combined Jordan-Palestine logistics + ustaz-led format priced RM 800+ below specialist competitors (Tabung Haji Travel, Andalusia).",
  },
  {
    slug: "japan-halal-7d-tokyo-osaka-kyoto",
    title: "Jepun Halal 7H — Tokyo, Osaka, Kyoto",
    destinationCountries: ["Japan"],
    durationDays: 7,
    durationNights: 5,
    region: "east_asia",
    halalTier: "halal_certified",
    audiences: ["family", "honeymoon", "shopping"],
    priceMyr: 4990,
    competitorPriceLowMyr: 5500,
    competitorPriceHighMyr: 7800,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "AirAsia X KUL-NRT/KIX return",
      "3-star hotels Tokyo + Osaka",
      "Halal-certified meals (Sekai Cafe, Naritaya, Ayam-ya)",
      "JR Pass 7-day or Shinkansen Tokyo-Osaka",
      "Mt Fuji 5th station, Kyoto Fushimi Inari, Osaka Castle",
      "Tokyo Camii visit (largest mosque in Japan)",
    ],
    exclusions: ["DisneySea/USJ tickets", "Lunches some days"],
    highlights: [
      "Solat di Tokyo Camii (Turkish-built mosque)",
      "Halal ramen at Naritaya & Ayam-ya",
      "Cherry blossom (Apr) or autumn momiji (Nov) departures",
    ],
    itinerarySummary: [
      "Day 1: KUL > Tokyo",
      "Day 2: Tokyo — Asakusa, Shibuya, Tokyo Camii",
      "Day 3: Mt Fuji + Hakone",
      "Day 4: Shinkansen to Kyoto, Fushimi Inari",
      "Day 5: Osaka — Dotonbori, Osaka Castle",
      "Day 6: USJ free day",
      "Day 7: KIX > KUL",
    ],
    prayerFacilities:
      "Prayer rooms at Narita/KIX, major malls; mosque list pre-loaded in app",
    halalFoodNotes:
      "Curated halal-certified restaurant list; bento halal pre-order on shinkansen",
    visaNotes: "Visa-free 90 days for Malaysians",
    bestMonths: ["Mar", "Apr", "Oct", "Nov"],
    minPax: 12,
    demand: "very_high",
    rationale:
      "Japan halal travel is the fastest-growing MY East Asia segment (+40% YoY). AirAsia X bulk + halal restaurant pre-arrangements (volume rates) achieve RM 500+ saving over Apple/Reliance.",
  },
  {
    slug: "korea-halal-7d-seoul-busan",
    title: "Korea Halal 7H — Seoul, Nami, Busan",
    destinationCountries: ["South Korea"],
    durationDays: 7,
    durationNights: 5,
    region: "east_asia",
    halalTier: "halal_certified",
    audiences: ["family", "honeymoon", "shopping"],
    priceMyr: 3990,
    competitorPriceLowMyr: 4500,
    competitorPriceHighMyr: 5800,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "Korean Air/AirAsia X KUL-ICN return",
      "3-star hotel Seoul + Busan",
      "Halal-certified breakfast + 3 dinners (Eid, Busan Yongdusan, Itaewon)",
      "Nami Island + Petite France",
      "Lotte World or Everland choice",
      "KTX Seoul-Busan",
      "Visit Seoul Central Mosque (Itaewon)",
    ],
    exclusions: ["Theme park add-ons", "Some lunches"],
    highlights: [
      "Solat Jumaat di Seoul Central Mosque",
      "Itaewon halal street",
      "Cherry blossom / autumn / ski-season variants",
    ],
    itinerarySummary: [
      "Day 1: KUL > Seoul",
      "Day 2: Nami + Petite France",
      "Day 3: Seoul city + Itaewon mosque",
      "Day 4: Theme park",
      "Day 5: KTX > Busan, Haeundae",
      "Day 6: Busan — Gamcheon, Yongdusan",
      "Day 7: PUS > KUL",
    ],
    prayerFacilities:
      "Itaewon mosque is hub; prayer rooms at ICN, Lotte World, COEX",
    halalFoodNotes:
      "EID, Murree, Busan Pakistan — pre-booked KMF-certified outlets",
    visaNotes:
      "K-ETA required (KRW 10,000); visa-free entry confirmed thereafter",
    bestMonths: ["Mar", "Apr", "May", "Sep", "Oct", "Nov"],
    minPax: 15,
    demand: "very_high",
    rationale:
      "K-wave demand intersects MY Muslim segment hard. Bundling KTX (most competitors use bus) at sub-RM 4k is a category-leading offer.",
  },
  {
    slug: "china-silk-road-xian-beijing-8d",
    title: "Silk Road China 8H — Beijing, Xi'an, Lanzhou",
    destinationCountries: ["China"],
    durationDays: 8,
    durationNights: 6,
    region: "east_asia",
    halalTier: "muslim_friendly",
    audiences: ["heritage", "family", "senior"],
    priceMyr: 3990,
    competitorPriceLowMyr: 4500,
    competitorPriceHighMyr: 5500,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "Xiamen Air/AirAsia KUL-PEK return",
      "4-star hotels (Hui-Muslim quarter Xi'an)",
      "Halal full board (Hui-Muslim restaurants)",
      "Tembok Besar, Forbidden City, Tiananmen",
      "Xi'an Terracotta Warriors + Great Mosque of Xi'an",
      "Lanzhou Yellow River + lamian experience",
      "Bullet train Beijing-Xi'an-Lanzhou",
    ],
    exclusions: ["Tipping CNY 250", "Optional Beijing duck (non-halal — skip)"],
    highlights: [
      "Solat Jumaat di Masjid Agung Xi'an (1300 tahun)",
      "Hui Muslim quarter food street",
      "Terracotta army UNESCO",
    ],
    itinerarySummary: [
      "Day 1-2: KUL > Beijing, Tembok Besar",
      "Day 3: Forbidden City, Tiananmen, Niujie Mosque",
      "Day 4: Bullet train Xi'an",
      "Day 5: Terracotta Warriors + Great Mosque",
      "Day 6: Train Lanzhou",
      "Day 7: Lanzhou Yellow River + return Beijing",
      "Day 8: PEK > KUL",
    ],
    prayerFacilities:
      "Hui Muslim mosques in Beijing (Niujie), Xi'an, Lanzhou — abundant",
    halalFoodNotes:
      "Hui qing zhen (清真) certified restaurants — fully halal lamian, kebab",
    visaNotes: "Visa-free 30 days for Malaysians (since 2024)",
    bestMonths: ["Apr", "May", "Sep", "Oct"],
    minPax: 18,
    demand: "rising",
    rationale:
      "Visa-free policy (Nov 2024) unlocked latent demand. Hui-Muslim heritage angle differentiates from generic China tours; few competitors run this routing at this price.",
  },
  {
    slug: "kashmir-paradise-7d",
    title: "Kashmir 7H — Srinagar, Gulmarg, Pahalgam, Sonmarg",
    destinationCountries: ["India"],
    durationDays: 7,
    durationNights: 5,
    region: "south_asia",
    halalTier: "muslim_majority",
    audiences: ["family", "honeymoon", "adventure"],
    priceMyr: 2990,
    competitorPriceLowMyr: 3500,
    competitorPriceHighMyr: 4500,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "AirAsia/IndiGo KUL-DEL-SXR",
      "Houseboat 2 nights + hotel 3 nights",
      "Halal full board",
      "Shikara ride Dal Lake",
      "Gulmarg gondola (Phase 1)",
      "Pahalgam, Sonmarg, Aru Valley",
    ],
    exclusions: ["Gondola Phase 2", "Pony rides", "Visa fee"],
    highlights: [
      "Kashmir Valley 96% Muslim — fully halal",
      "Solat di Hazratbal Shrine",
      "Snow at Gulmarg (Dec-Mar) or tulip (Apr)",
    ],
    itinerarySummary: [
      "Day 1: KUL > Delhi > Srinagar",
      "Day 2: Houseboat + Shikara",
      "Day 3: Gulmarg",
      "Day 4: Pahalgam",
      "Day 5: Sonmarg",
      "Day 6: Srinagar shopping",
      "Day 7: SXR > KUL",
    ],
    prayerFacilities: "Mosque in every village; houseboat has prayer mat",
    halalFoodNotes: "100% halal — wazwan cuisine",
    visaNotes: "India e-Visa USD 25 for Malaysians",
    bestMonths: ["Apr", "May", "Jun", "Sep", "Oct", "Dec", "Jan"],
    minPax: 6,
    demand: "rising",
    rationale:
      "Bali-alternative trend: Muslim-majority valley with snow/tulip seasons priced under RM 3k. Houseboat inclusion at this price unmatched by Andalusia/Bumi Hijrah.",
  },
  {
    slug: "georgia-azerbaijan-caucasus-10d",
    title: "Caucasus 10H — Georgia & Azerbaijan",
    destinationCountries: ["Georgia", "Azerbaijan"],
    durationDays: 10,
    durationNights: 8,
    region: "caucasus",
    halalTier: "muslim_friendly",
    audiences: ["heritage", "adventure", "family"],
    priceMyr: 4990,
    competitorPriceLowMyr: 5500,
    competitorPriceHighMyr: 7000,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "Qatar Airways KUL-DOH-TBS / BAK-DOH-KUL",
      "4-star hotels Tbilisi, Kazbegi, Baku",
      "Halal breakfast + dinner",
      "Mtskheta, Kazbegi (Gergeti), Sighnaghi wine valley (skip wine)",
      "Border crossing Georgia > Azerbaijan",
      "Baku old city, Heydar Aliyev Center, Gobustan mud volcanoes",
    ],
    exclusions: ["Lunches", "Cable car at some sites"],
    highlights: [
      "Azerbaijan 96% Muslim — halal default",
      "Snow-capped Caucasus mountains",
      "Baku Flame Towers + Caspian Sea",
    ],
    itinerarySummary: [
      "Day 1-2: KUL > Tbilisi",
      "Day 3-4: Kazbegi, Ananuri",
      "Day 5: Sighnaghi region",
      "Day 6: Cross to Baku (overland or flight)",
      "Day 7-8: Baku old city + Gobustan",
      "Day 9: Quba mountain villages",
      "Day 10: BAK > KUL",
    ],
    prayerFacilities: "Azerbaijan side abundant; Georgia mosque in Tbilisi & Batumi",
    halalFoodNotes:
      "Azerbaijan all halal; Georgia agency uses halal-certified restaurants",
    visaNotes: "Both countries visa-free 1 year for Malaysians",
    bestMonths: ["May", "Jun", "Sep", "Oct"],
    minPax: 15,
    demand: "rising",
    rationale:
      "Visa-free + Qatar Airways open-jaw beats one-way circuit competitors. Sub-RM 5k Caucasus product is rare — most listed at RM 5,500-7,000.",
  },
  {
    slug: "kyrgyzstan-nomad-8d",
    title: "Kyrgyzstan Nomad Trail 8H — Bishkek, Issyk-Kul, Song Kol",
    destinationCountries: ["Kyrgyzstan"],
    durationDays: 8,
    durationNights: 6,
    region: "central_asia",
    halalTier: "muslim_majority",
    audiences: ["adventure", "heritage"],
    priceMyr: 4490,
    competitorPriceLowMyr: 5000,
    competitorPriceHighMyr: 6500,
    savingsVsMarketMyr: 510,
    currency: "MYR",
    inclusions: [
      "Pegasus/Turkish KUL-IST-FRU",
      "3-4 star hotels + 1 night yurt camp Song Kol",
      "Halal full board",
      "Ala Archa, Burana Tower, Cholpon-Ata, Karakol",
      "Eagle hunter demonstration",
      "Skazka Canyon",
    ],
    exclusions: ["Horse riding (USD 15/hr)"],
    highlights: [
      "90% Muslim — fully halal",
      "Yurt camp under stars at 3,000m Song Kol",
      "Lake Issyk-Kul (2nd largest alpine lake in world)",
    ],
    itinerarySummary: [
      "Day 1-2: KUL > Bishkek via IST",
      "Day 3: Bishkek + Ala Archa",
      "Day 4: Burana > Cholpon-Ata",
      "Day 5: Karakol + Jety-Oguz",
      "Day 6: Song Kol yurt camp",
      "Day 7: Bishkek",
      "Day 8: FRU > KUL",
    ],
    prayerFacilities: "Mosques in every town; yurt camp has prayer mat & qibla",
    halalFoodNotes: "Beshbarmak, manti, samsa — all halal",
    visaNotes: "Visa-free 60 days for Malaysians",
    bestMonths: ["Jun", "Jul", "Aug", "Sep"],
    minPax: 10,
    demand: "niche",
    rationale:
      "Niche but rapidly rising adventure-Muslim segment (Insta/TikTok driver). Most competitors don't run yurt camps — direct supplier contracts at Song Kol enable RM 500+ saving.",
  },
  {
    slug: "phuket-krabi-family-5d",
    title: "Phuket & Krabi Halal Family 5H",
    destinationCountries: ["Thailand"],
    durationDays: 5,
    durationNights: 4,
    region: "southeast_asia",
    halalTier: "muslim_friendly",
    audiences: ["family", "honeymoon"],
    priceMyr: 1190,
    competitorPriceLowMyr: 1450,
    competitorPriceHighMyr: 2200,
    savingsVsMarketMyr: 260,
    currency: "MYR",
    inclusions: [
      "AirAsia KUL-HKT return",
      "3-star halal-friendly hotel Patong / Karon (4 nights)",
      "Halal breakfast",
      "Phi Phi island day tour with halal lunch",
      "James Bond / Phang Nga day tour",
      "Krabi day trip",
    ],
    exclusions: ["Some dinners", "Ferry to Krabi (RM 80)"],
    highlights: [
      "Phuket has 30% Muslim population — many halal restaurants",
      "Patong Mosque + Bang Tao Mosque",
      "Phi Phi Maya Bay snorkel",
    ],
    itinerarySummary: [
      "Day 1: KUL > Phuket, Patong beach",
      "Day 2: Phi Phi day tour",
      "Day 3: Phang Nga / James Bond",
      "Day 4: Krabi Railay",
      "Day 5: HKT > KUL",
    ],
    prayerFacilities: "Phuket has 50+ mosques; surau on most islands",
    halalFoodNotes:
      "Pre-vetted halal restaurant list (Asia Tom Yum, Halal Patong, Salaam)",
    visaNotes: "Visa-free 30 days for Malaysians",
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
    minPax: 4,
    demand: "very_high",
    rationale:
      "Sub-RM 1,200 island package is category-defining. Repeat-business engine for B40/M40 family segment. Halal vetting differentiates from generic Phuket OTAs.",
  },
  {
    slug: "albania-macedonia-balkans2-10d",
    title: "Balkan Hidden Gems 10H — Albania, Macedonia, Kosovo",
    destinationCountries: ["Albania", "North Macedonia", "Kosovo"],
    durationDays: 10,
    durationNights: 8,
    region: "balkans",
    halalTier: "muslim_majority",
    audiences: ["heritage", "honeymoon"],
    priceMyr: 5990,
    competitorPriceLowMyr: 6800,
    competitorPriceHighMyr: 8500,
    savingsVsMarketMyr: 810,
    currency: "MYR",
    inclusions: [
      "Turkish Airlines KUL-IST-TIA",
      "4-star hotels",
      "Halal full board",
      "Tirana, Shkoder, Berat, Gjirokaster, Saranda",
      "Ohrid (Macedonia) + Prizren (Kosovo)",
      "Albanian Riviera coastal drive",
    ],
    exclusions: ["Lunches", "Albanian Alps optional add-on"],
    highlights: [
      "Albania ~60% Muslim, Kosovo ~95%, Macedonia ~33%",
      "Et'hem Bey Mosque Tirana, Sinan Pasha Mosque Prizren",
      "Berat — UNESCO town of a thousand windows",
    ],
    itinerarySummary: [
      "Day 1-2: KUL > Tirana",
      "Day 3: Kruje + Shkoder",
      "Day 4: Berat",
      "Day 5: Gjirokaster + Saranda",
      "Day 6: Cross to Ohrid",
      "Day 7: Skopje",
      "Day 8: Prizren (Kosovo)",
      "Day 9: Return Tirana",
      "Day 10: TIA > KUL",
    ],
    prayerFacilities: "Mosques throughout — Ottoman heritage architecture",
    halalFoodNotes: "Native halal cuisine — qofte, byrek, tave kosi",
    visaNotes: "All three visa-free for Malaysians (90 days each)",
    bestMonths: ["May", "Jun", "Sep", "Oct"],
    minPax: 15,
    demand: "rising",
    rationale:
      "Hidden-gem alternative to Bosnia trend. Three Muslim-majority countries on one circuit, all visa-free. RM 800+ undercut achievable due to low B2B land costs (under-touristed market).",
  },
  {
    slug: "pattani-hatyai-malay-heritage-4d",
    title: "Pattani & Hatyai Malay Heritage 4H",
    destinationCountries: ["Thailand"],
    durationDays: 4,
    durationNights: 3,
    region: "southeast_asia",
    halalTier: "muslim_majority",
    audiences: ["family", "heritage", "shopping"],
    priceMyr: 490,
    competitorPriceLowMyr: 650,
    competitorPriceHighMyr: 950,
    savingsVsMarketMyr: 160,
    currency: "MYR",
    inclusions: [
      "Coach KL > Hatyai > Pattani > KL",
      "3-star halal hotel Hatyai (2N) + Pattani (1N)",
      "Halal breakfast",
      "Masjid Kerisik (oldest in Pattani)",
      "Floating market Klong Hae",
      "Asean Trade shopping",
    ],
    exclusions: ["Lunch & dinner", "Personal shopping"],
    highlights: [
      "Pattani 80% Muslim Melayu",
      "Solat di Masjid Kerisik (legenda)",
      "Halal nasi dagang & nasi kerabu",
    ],
    itinerarySummary: [
      "Day 1: KL > Hatyai (overnight coach)",
      "Day 2: Hatyai shopping + floating market",
      "Day 3: Pattani — Masjid Kerisik, makam Tok Pasai",
      "Day 4: Hatyai > KL",
    ],
    prayerFacilities: "Mosques in every kampung; surau in coach stops",
    halalFoodNotes: "100% halal Malay-Thai fusion",
    visaNotes: "Visa-free 30 days for Malaysians; PASS Lapor required",
    bestMonths: ["Jan", "Feb", "Mar", "Jul", "Aug", "Nov", "Dec"],
    minPax: 30,
    demand: "high",
    rationale:
      "Ultra-budget heritage segment for B40 from Northern states. Coach-based logistics drops cost dramatically; few national agencies run this — mostly Kelantan-based operators.",
  },
  {
    slug: "bali-halal-5d-private-villa",
    title: "Bali Halal 5H — Ubud & Seminyak Halal Villa",
    destinationCountries: ["Indonesia"],
    durationDays: 5,
    durationNights: 4,
    region: "southeast_asia",
    halalTier: "muslim_friendly",
    audiences: ["honeymoon", "family"],
    priceMyr: 1490,
    competitorPriceLowMyr: 1750,
    competitorPriceHighMyr: 2600,
    savingsVsMarketMyr: 260,
    currency: "MYR",
    inclusions: [
      "AirAsia KUL-DPS return",
      "3-star halal-certified hotel/villa Seminyak + Ubud",
      "Halal breakfast + 2 dinners",
      "Tegalalang rice terrace, Tanah Lot, Uluwatu",
      "Ubud Monkey Forest + market",
      "Pre-arranged halal restaurants (Warung Mak Beng halal section, Krishna)",
    ],
    exclusions: ["Spa", "Watersports"],
    highlights: [
      "Curated halal villa (Bali Indonesia Muslim village option)",
      "Solat at An-Nur Denpasar mosque",
      "Sunset at Tanah Lot",
    ],
    itinerarySummary: [
      "Day 1: KUL > Bali, Seminyak",
      "Day 2: Tanah Lot + Uluwatu",
      "Day 3: Ubud — Tegalalang + Monkey Forest",
      "Day 4: Beach + shopping",
      "Day 5: DPS > KUL",
    ],
    prayerFacilities:
      "Bali ~13% Muslim; mosque in Denpasar, Kuta, Seminyak — list provided",
    halalFoodNotes:
      "Curated halal-certified outlets only; villa kitchen halal-stocked",
    visaNotes: "Visa-on-arrival waived for Malaysians (visa-free 30 days)",
    bestMonths: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    minPax: 2,
    demand: "high",
    rationale:
      "Bali-with-halal-confidence is underserved — most OTAs ignore halal vetting. RM 1,490 with curated halal restaurant list undercuts halal-specialist Tripfez (RM 1,750+).",
  },
];

export const totalPackages = halalTravelPackages.length;
